/**
 * Land Vehicle Types Seed Data
 * Based on DoD vehicle specifications from FM 55-15 and technical manuals
 */

import { db } from "../db";
import { landVehicleTypes } from "@shared/schema";

export const landVehicleSeeds = [
  {
    code: "LMTV",
    name: "M1078 Light Medium Tactical Vehicle",
    category: "light_tactical",
    payload_lbs: 5000,
    curb_weight_lbs: 13000,
    gross_weight_lbs: 18000,
    length_in: "253",
    width_in: "96",
    height_in: "105.5",
    bed_length_in: "144",
    bed_width_in: "94",
    max_speed_mph: 58,
    range_miles: 400,
    fuel_capacity_gal: "55",
    fuel_consumption_mpg: "10",
    fuel_type: "diesel",
    axle_config: "4x4",
    can_tow_trailer: true,
    max_tow_weight_lbs: 12000,
    pallet_capacity_463l: 2,
    pallet_capacity_40x48: 4,
    passenger_capacity: 20,
    notes: "2.5-ton truck, workhorse medium truck. 225 hp Caterpillar 6.6L diesel, runs on Diesel/JP-4/JP-8. Fold-down sides for troop transport. Optional 1,500 lb loader crane.",
  },
  {
    code: "FMTV_5T",
    name: "M1083 Family of Medium Tactical Vehicles (5-ton)",
    category: "medium_tactical",
    payload_lbs: 10000,
    curb_weight_lbs: 19000,
    gross_weight_lbs: 29000,
    length_in: "276",
    width_in: "96",
    height_in: "114",
    bed_length_in: "168",
    bed_width_in: "94",
    max_speed_mph: 58,
    range_miles: 350,
    fuel_capacity_gal: "75",
    fuel_consumption_mpg: "6",
    fuel_type: "diesel",
    axle_config: "6x6",
    can_tow_trailer: true,
    max_tow_weight_lbs: 21000,
    pallet_capacity_463l: 2,
    pallet_capacity_40x48: 6,
    passenger_capacity: 24,
    notes: "5-ton variant of FMTV family. 330 hp Caterpillar engine, 6x6 drivetrain for increased off-road capability.",
  },
  {
    code: "HEMTT_CARGO",
    name: "M977A4 Heavy Expanded Mobility Tactical Truck (Cargo)",
    category: "heavy_tactical",
    payload_lbs: 20000,
    curb_weight_lbs: 27000,
    gross_weight_lbs: 47000,
    length_in: "396",
    width_in: "96",
    height_in: "116",
    bed_length_in: "240",
    bed_width_in: "96",
    max_speed_mph: 57,
    range_miles: 300,
    fuel_capacity_gal: "150",
    fuel_consumption_mpg: "3",
    fuel_type: "jp8",
    axle_config: "8x8",
    can_tow_trailer: true,
    max_tow_weight_lbs: 37000,
    pallet_capacity_463l: 4,
    pallet_capacity_40x48: 10,
    passenger_capacity: 4,
    notes: "10-ton cargo HEMTT. 450 hp Detroit Diesel. Provides heavy transport for combat vehicles and weapons systems.",
  },
  {
    code: "HEMTT_TANKER",
    name: "M978A4 HEMTT Fuel Tanker",
    category: "heavy_tactical",
    payload_lbs: 20000,
    curb_weight_lbs: 25000,
    gross_weight_lbs: 45000,
    length_in: "396",
    width_in: "96",
    height_in: "120",
    bed_length_in: "0",
    bed_width_in: "0",
    max_speed_mph: 55,
    range_miles: 300,
    fuel_capacity_gal: "2500",
    fuel_consumption_mpg: "3",
    fuel_type: "jp8",
    axle_config: "8x8",
    can_tow_trailer: true,
    max_tow_weight_lbs: 25000,
    pallet_capacity_463l: 0,
    pallet_capacity_40x48: 0,
    passenger_capacity: 2,
    notes: "Fuel tanker variant. Carries up to 9,500L (2,500 gal) of fuel. Essential for forward refueling operations.",
  },
  {
    code: "HEMTT_WRECKER",
    name: "M984A4 HEMTT Wrecker",
    category: "heavy_tactical",
    payload_lbs: 22000,
    curb_weight_lbs: 32000,
    gross_weight_lbs: 54000,
    length_in: "420",
    width_in: "96",
    height_in: "132",
    bed_length_in: "180",
    bed_width_in: "96",
    max_speed_mph: 50,
    range_miles: 280,
    fuel_capacity_gal: "150",
    fuel_consumption_mpg: "2.5",
    fuel_type: "jp8",
    axle_config: "8x8",
    can_tow_trailer: false,
    max_tow_weight_lbs: 0,
    pallet_capacity_463l: 0,
    pallet_capacity_40x48: 0,
    passenger_capacity: 2,
    notes: "10-ton recovery truck. 11,000 lb winch and heavy recovery boom. Can pull disabled vehicles onto its bed.",
  },
  {
    code: "PLS",
    name: "M1075/M1084 Palletized Load System",
    category: "heavy_tactical",
    payload_lbs: 20000,
    curb_weight_lbs: 28000,
    gross_weight_lbs: 48000,
    length_in: "396",
    width_in: "96",
    height_in: "120",
    bed_length_in: "240",
    bed_width_in: "96",
    max_speed_mph: 55,
    range_miles: 300,
    fuel_capacity_gal: "150",
    fuel_consumption_mpg: "3",
    fuel_type: "jp8",
    axle_config: "10x10",
    can_tow_trailer: true,
    max_tow_weight_lbs: 33000,
    pallet_capacity_463l: 4,
    pallet_capacity_40x48: 10,
    passenger_capacity: 2,
    notes: "Uses 20' flatracks for cargo containers or bundled supplies. Demountable cargo capability.",
  },
  {
    code: "HET",
    name: "M1070 Heavy Equipment Transporter",
    category: "transport",
    payload_lbs: 140000,
    curb_weight_lbs: 45000,
    gross_weight_lbs: 185000,
    length_in: "360",
    width_in: "132",
    height_in: "144",
    bed_length_in: "600",
    bed_width_in: "132",
    max_speed_mph: 45,
    range_miles: 250,
    fuel_capacity_gal: "200",
    fuel_consumption_mpg: "2",
    fuel_type: "diesel",
    axle_config: "8x6",
    can_tow_trailer: true,
    max_tow_weight_lbs: 200000,
    pallet_capacity_463l: 0,
    pallet_capacity_40x48: 0,
    passenger_capacity: 2,
    notes: "Tank transporter with M1000 semi-trailer. Hauls M1 Abrams tanks (~70 tons). 500-700 hp diesel engine.",
  },
  {
    code: "MTVR",
    name: "MK23 Medium Tactical Vehicle Replacement",
    category: "medium_tactical",
    payload_lbs: 14000,
    curb_weight_lbs: 22000,
    gross_weight_lbs: 36000,
    length_in: "300",
    width_in: "99",
    height_in: "120",
    bed_length_in: "184",
    bed_width_in: "96",
    max_speed_mph: 65,
    range_miles: 350,
    fuel_capacity_gal: "80",
    fuel_consumption_mpg: "5",
    fuel_type: "jp8",
    axle_config: "6x6",
    can_tow_trailer: true,
    max_tow_weight_lbs: 30000,
    pallet_capacity_463l: 3,
    pallet_capacity_40x48: 8,
    passenger_capacity: 22,
    notes: "Marine Corps standard medium truck. 7-ton off-road / 15-ton road payload. 425 hp Caterpillar diesel.",
  },
  {
    code: "HMMWV",
    name: "M1151 High Mobility Multipurpose Wheeled Vehicle",
    category: "light_tactical",
    payload_lbs: 2500,
    curb_weight_lbs: 5200,
    gross_weight_lbs: 7700,
    length_in: "180",
    width_in: "85",
    height_in: "72",
    bed_length_in: "60",
    bed_width_in: "54",
    max_speed_mph: 70,
    range_miles: 350,
    fuel_capacity_gal: "25",
    fuel_consumption_mpg: "12",
    fuel_type: "diesel",
    axle_config: "4x4",
    can_tow_trailer: true,
    max_tow_weight_lbs: 4500,
    pallet_capacity_463l: 0,
    pallet_capacity_40x48: 1,
    passenger_capacity: 4,
    notes: "Humvee light utility vehicle. Various configurations: ambulance, troop carrier, weapons platform.",
  },
  {
    code: "M915A5",
    name: "M915A5 Line Haul Tractor",
    category: "transport",
    payload_lbs: 0,
    curb_weight_lbs: 19000,
    gross_weight_lbs: 19000,
    length_in: "288",
    width_in: "102",
    height_in: "120",
    bed_length_in: "0",
    bed_width_in: "0",
    max_speed_mph: 65,
    range_miles: 500,
    fuel_capacity_gal: "150",
    fuel_consumption_mpg: "5",
    fuel_type: "diesel",
    axle_config: "6x4",
    can_tow_trailer: true,
    max_tow_weight_lbs: 68000,
    pallet_capacity_463l: 0,
    pallet_capacity_40x48: 0,
    passenger_capacity: 2,
    notes: "Line haul tractor truck. Pulls semi-trailers for long-distance transport. 350 hp Detroit Diesel.",
  },
];

export async function seedLandVehicles() {
  console.log("[Seed] Seeding land vehicle types...");
  
  for (const vehicle of landVehicleSeeds) {
    try {
      await db.insert(landVehicleTypes).values(vehicle).onConflictDoNothing();
      console.log(`[Seed] Added vehicle: ${vehicle.code}`);
    } catch (error) {
      console.error(`[Seed] Error adding ${vehicle.code}:`, error);
    }
  }
  
  console.log("[Seed] Land vehicle seeding complete");
}
