/**
 * MSC (Military Sealift Command) Vessel Types Seed Data
 * Based on actual MSC fleet specifications and naval documentation
 * Hull designations: T-AO (Oiler), T-AKR (Cargo), T-EPF (Fast Transport), etc.
 */

import { db } from "../db";
import { seaVesselTypes } from "@shared/schema";

export const seaVesselSeeds = [
  {
    code: "T-AO-187",
    name: "Henry J. Kaiser-class Fleet Replenishment Oiler",
    hull_prefix: "T-AO",
    category: "oiler",
    cargo_capacity_lbs: 0,
    teu_capacity: 0,
    fuel_capacity_barrels: 180000,
    vehicle_capacity: 0,
    lane_meters: 0,
    displacement_tons: 41353,
    deadweight_tons: 25000,
    length_ft: 677,
    beam_ft: 97,
    draft_ft: 36,
    max_speed_knots: 20,
    cruise_speed_knots: 15,
    range_nm: 6000,
    crew_size: 89,
    has_crane: true,
    crane_capacity_tons: 30,
    has_roro_capability: false,
    has_helicopter_deck: true,
    active_fleet_count: 15,
    notes: "Primary underway replenishment oiler for the Navy. Carries JP-5 jet fuel, DFM, and cargo. 16 ships in class. Dual delivery systems for UNREP operations.",
  },
  {
    code: "T-AKE-1",
    name: "Lewis and Clark-class Dry Cargo/Ammunition Ship",
    hull_prefix: "T-AKE",
    category: "combat_logistics",
    cargo_capacity_lbs: 13600000,
    teu_capacity: 0,
    fuel_capacity_barrels: 23500,
    vehicle_capacity: 0,
    lane_meters: 0,
    displacement_tons: 41000,
    deadweight_tons: 18700,
    length_ft: 689,
    beam_ft: 106,
    draft_ft: 30,
    max_speed_knots: 20,
    cruise_speed_knots: 15,
    range_nm: 14000,
    crew_size: 124,
    has_crane: true,
    crane_capacity_tons: 50,
    has_roro_capability: false,
    has_helicopter_deck: true,
    active_fleet_count: 14,
    notes: "Combat logistics force ship providing ammunition, provisions, and stores. 14 ships in class. Can transfer cargo while underway via CONREP/VERTREP.",
  },
  {
    code: "LMSR-BOB_HOPE",
    name: "Bob Hope-class Large, Medium-Speed Roll-on/Roll-off",
    hull_prefix: "T-AKR",
    category: "cargo",
    cargo_capacity_lbs: 98000000,
    teu_capacity: 1300,
    fuel_capacity_barrels: 12500,
    vehicle_capacity: 1000,
    lane_meters: 50000,
    displacement_tons: 62069,
    deadweight_tons: 35000,
    length_ft: 951,
    beam_ft: 106,
    draft_ft: 36,
    max_speed_knots: 24,
    cruise_speed_knots: 20,
    range_nm: 12000,
    crew_size: 30,
    has_crane: true,
    crane_capacity_tons: 110,
    has_roro_capability: true,
    has_helicopter_deck: true,
    active_fleet_count: 7,
    notes: "Largest sealift ships in MSC fleet. Can carry an entire Army armored battalion. 7 ships: Bob Hope, Fisher, Seay, Mendonca, Pililaau, Brittin, Benavidez.",
  },
  {
    code: "LMSR-WATSON",
    name: "Watson-class Large, Medium-Speed Roll-on/Roll-off",
    hull_prefix: "T-AKR",
    category: "cargo",
    cargo_capacity_lbs: 95000000,
    teu_capacity: 1200,
    fuel_capacity_barrels: 11000,
    vehicle_capacity: 950,
    lane_meters: 48000,
    displacement_tons: 63276,
    deadweight_tons: 36000,
    length_ft: 951,
    beam_ft: 106,
    draft_ft: 36,
    max_speed_knots: 24,
    cruise_speed_knots: 20,
    range_nm: 12000,
    crew_size: 30,
    has_crane: true,
    crane_capacity_tons: 110,
    has_roro_capability: true,
    has_helicopter_deck: true,
    active_fleet_count: 8,
    notes: "Second class of LMSRs. 8 ships: Watson, Sisler, Dahl, Red Cloud, Charlton, Watkins, Pomeroy, Soderman. Enhanced vehicle deck capacity.",
  },
  {
    code: "T-EPF",
    name: "Spearhead-class Expeditionary Fast Transport",
    hull_prefix: "T-EPF",
    category: "transport",
    cargo_capacity_lbs: 1200000,
    teu_capacity: 40,
    fuel_capacity_barrels: 3500,
    vehicle_capacity: 40,
    lane_meters: 2000,
    displacement_tons: 2362,
    deadweight_tons: 600,
    length_ft: 338,
    beam_ft: 93,
    draft_ft: 15,
    max_speed_knots: 43,
    cruise_speed_knots: 35,
    range_nm: 1200,
    crew_size: 26,
    has_crane: true,
    crane_capacity_tons: 20,
    has_roro_capability: true,
    has_helicopter_deck: true,
    active_fleet_count: 14,
    notes: "High-speed catamaran for rapid intra-theater transport. 43+ knot capability. Can carry 312 troops + vehicles. 14 ships built/planned.",
  },
  {
    code: "T-AOT-1123",
    name: "Champion-class Fleet Ocean Tug",
    hull_prefix: "T-AOT",
    category: "support",
    cargo_capacity_lbs: 0,
    teu_capacity: 0,
    fuel_capacity_barrels: 2000,
    vehicle_capacity: 0,
    lane_meters: 0,
    displacement_tons: 2260,
    deadweight_tons: 850,
    length_ft: 235,
    beam_ft: 42,
    draft_ft: 15,
    max_speed_knots: 16,
    cruise_speed_knots: 12,
    range_nm: 8000,
    crew_size: 22,
    has_crane: false,
    crane_capacity_tons: 0,
    has_roro_capability: false,
    has_helicopter_deck: false,
    active_fleet_count: 4,
    notes: "Ocean-going tug for towing disabled vessels and providing salvage support. 8,000 HP bollard pull capacity.",
  },
  {
    code: "MV-CAPE",
    name: "Cape-class Cargo Ship (Ready Reserve Force)",
    hull_prefix: "MV",
    category: "cargo",
    cargo_capacity_lbs: 44000000,
    teu_capacity: 800,
    fuel_capacity_barrels: 8000,
    vehicle_capacity: 200,
    lane_meters: 10000,
    displacement_tons: 33000,
    deadweight_tons: 22000,
    length_ft: 648,
    beam_ft: 90,
    draft_ft: 32,
    max_speed_knots: 18,
    cruise_speed_knots: 14,
    range_nm: 10000,
    crew_size: 35,
    has_crane: true,
    crane_capacity_tons: 60,
    has_roro_capability: false,
    has_helicopter_deck: false,
    active_fleet_count: 12,
    notes: "Ready Reserve Force cargo ships. Maintained in reduced operating status. Can activate within 5-10 days for surge sealift.",
  },
  {
    code: "T-AH-19",
    name: "Mercy-class Hospital Ship",
    hull_prefix: "T-AH",
    category: "medical",
    cargo_capacity_lbs: 500000,
    teu_capacity: 0,
    fuel_capacity_barrels: 10000,
    vehicle_capacity: 0,
    lane_meters: 0,
    displacement_tons: 69360,
    deadweight_tons: 24000,
    length_ft: 894,
    beam_ft: 106,
    draft_ft: 33,
    max_speed_knots: 17,
    cruise_speed_knots: 12,
    range_nm: 13000,
    crew_size: 63,
    has_crane: true,
    crane_capacity_tons: 25,
    has_roro_capability: false,
    has_helicopter_deck: true,
    active_fleet_count: 2,
    notes: "1,000-bed hospital ship. USNS Mercy (T-AH 19) and USNS Comfort (T-AH 20). 12 ORs, CT scanner, pharmacy, labs. Humanitarian missions.",
  },
  {
    code: "T-AVB-3",
    name: "Aviation Logistics Support Ship",
    hull_prefix: "T-AVB",
    category: "support",
    cargo_capacity_lbs: 16000000,
    teu_capacity: 150,
    fuel_capacity_barrels: 6000,
    vehicle_capacity: 50,
    lane_meters: 5000,
    displacement_tons: 24500,
    deadweight_tons: 11000,
    length_ft: 602,
    beam_ft: 90,
    draft_ft: 28,
    max_speed_knots: 18,
    cruise_speed_knots: 14,
    range_nm: 10000,
    crew_size: 32,
    has_crane: true,
    crane_capacity_tons: 70,
    has_roro_capability: true,
    has_helicopter_deck: true,
    active_fleet_count: 2,
    notes: "Aviation intermediate maintenance activity (AIMA) at sea. Supports deployed aircraft squadrons. USNS Wright and USNS Curtiss.",
  },
  {
    code: "T-AKR-SHUGHART",
    name: "Shughart-class Roll-on/Roll-off",
    hull_prefix: "T-AKR",
    category: "cargo",
    cargo_capacity_lbs: 72000000,
    teu_capacity: 500,
    fuel_capacity_barrels: 8500,
    vehicle_capacity: 700,
    lane_meters: 35000,
    displacement_tons: 55123,
    deadweight_tons: 32000,
    length_ft: 906,
    beam_ft: 105,
    draft_ft: 34,
    max_speed_knots: 24,
    cruise_speed_knots: 20,
    range_nm: 11000,
    crew_size: 28,
    has_crane: true,
    crane_capacity_tons: 90,
    has_roro_capability: true,
    has_helicopter_deck: true,
    active_fleet_count: 4,
    notes: "Medium-speed RO/RO for armored vehicle transport. Named for Medal of Honor recipients. Shughart, Gordon, Yano, Gilliland.",
  },
];

export async function seedSeaVessels() {
  console.log("[Seed] Seeding MSC vessel types...");
  
  for (const vessel of seaVesselSeeds) {
    try {
      await db.insert(seaVesselTypes).values(vessel).onConflictDoNothing();
      console.log(`[Seed] Added vessel type: ${vessel.code}`);
    } catch (error) {
      console.error(`[Seed] Error adding ${vessel.code}:`, error);
    }
  }
  
  console.log("[Seed] MSC vessel seeding complete");
}
