/**
 * Warehouse PDF Utilities
 * 
 * Shared utilities for generating consistent, professional PDF documents
 * across all warehouse management system exports.
 */

import { jsPDF } from 'jspdf';

export const ARKA_COLORS = {
  primary: '#004E89',
  primaryRgb: [0, 78, 137] as [number, number, number],
  success: '#16A34A',
  successRgb: [22, 163, 74] as [number, number, number],
  warning: '#F59E0B',
  warningRgb: [245, 158, 11] as [number, number, number],
  danger: '#DC2626',
  dangerRgb: [220, 38, 38] as [number, number, number],
  muted: '#6B7280',
  mutedRgb: [107, 114, 128] as [number, number, number],
  text: '#374151',
  textRgb: [55, 65, 81] as [number, number, number],
  background: '#F3F4F6',
  backgroundRgb: [243, 244, 246] as [number, number, number],
  white: '#FFFFFF',
  whiteRgb: [255, 255, 255] as [number, number, number],
  border: '#E5E7EB',
  borderRgb: [229, 231, 235] as [number, number, number],
} as const;

export const PDF_MARGINS = {
  top: 15,
  bottom: 20,
  left: 15,
  right: 15,
};

export function hexToRgb(hex: string): [number, number, number] {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  return result
    ? [parseInt(result[1], 16), parseInt(result[2], 16), parseInt(result[3], 16)]
    : [0, 0, 0];
}

export function formatMilitaryDate(date?: Date): string {
  const d = date || new Date();
  const day = d.getDate().toString().padStart(2, '0');
  const months = ['JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC'];
  const month = months[d.getMonth()];
  const year = d.getFullYear().toString().slice(-2);
  const hours = d.getUTCHours().toString().padStart(2, '0');
  const mins = d.getUTCMinutes().toString().padStart(2, '0');
  return `${day}${month}${year} ${hours}${mins}Z`;
}

export function formatReportDate(date?: Date): string {
  const d = date || new Date();
  return d.toLocaleString('en-US', {
    year: 'numeric',
    month: 'short',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
    hour12: false,
    timeZoneName: 'short',
  });
}

export function addPdfHeader(
  doc: jsPDF,
  title: string,
  subtitle?: string,
  headerHeight: number = 22
): number {
  const pageWidth = doc.internal.pageSize.getWidth();

  doc.setFillColor(...ARKA_COLORS.primaryRgb);
  doc.rect(0, 0, pageWidth, headerHeight, 'F');

  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...ARKA_COLORS.whiteRgb);
  doc.text(title.toUpperCase(), pageWidth / 2, headerHeight / 2, { align: 'center' });

  if (subtitle) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(subtitle, pageWidth / 2, headerHeight / 2 + 6, { align: 'center' });
  }

  return headerHeight + 8;
}

export function addPdfFooter(
  doc: jsPDF,
  pageNum: number,
  totalPages: number
): void {
  const pageHeight = doc.internal.pageSize.getHeight();
  const pageWidth = doc.internal.pageSize.getWidth();

  doc.setDrawColor(...ARKA_COLORS.borderRgb);
  doc.setLineWidth(0.3);
  doc.line(PDF_MARGINS.left, pageHeight - 15, pageWidth - PDF_MARGINS.right, pageHeight - 15);

  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...ARKA_COLORS.mutedRgb);
  doc.text(`Page ${pageNum} of ${totalPages}`, pageWidth / 2, pageHeight - 8, { align: 'center' });
  doc.text('Generated by ARKA WMS', pageWidth - PDF_MARGINS.right, pageHeight - 8, { align: 'right' });
  doc.text(formatMilitaryDate(), PDF_MARGINS.left, pageHeight - 8, { align: 'left' });
}

export function addAllPageFooters(doc: jsPDF): void {
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addPdfFooter(doc, i, totalPages);
  }
}

export function addMetricBox(
  doc: jsPDF,
  x: number,
  y: number,
  width: number,
  height: number,
  label: string,
  value: string,
  valueColor: [number, number, number] = ARKA_COLORS.primaryRgb
): void {
  doc.setFillColor(...ARKA_COLORS.backgroundRgb);
  doc.roundedRect(x, y, width, height, 2, 2, 'F');

  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...ARKA_COLORS.textRgb);
  doc.text(label.toUpperCase(), x + width / 2, y + 8, { align: 'center' });

  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...valueColor);
  doc.text(value, x + width / 2, y + height - 6, { align: 'center' });
}

export function addSectionHeader(
  doc: jsPDF,
  y: number,
  title: string
): number {
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...ARKA_COLORS.textRgb);
  doc.text(title.toUpperCase(), PDF_MARGINS.left, y);
  
  doc.setDrawColor(...ARKA_COLORS.primaryRgb);
  doc.setLineWidth(0.5);
  const titleWidth = doc.getTextWidth(title.toUpperCase());
  doc.line(PDF_MARGINS.left, y + 1, PDF_MARGINS.left + titleWidth, y + 1);
  
  return y + 6;
}

export function createPdfDocument(orientation: 'portrait' | 'landscape' = 'portrait'): jsPDF {
  return new jsPDF({
    orientation,
    unit: 'mm',
    format: 'a4',
  });
}

export function generatePdfFilename(prefix: string, siteName?: string): string {
  const safeSiteName = siteName ? `_${siteName.replace(/\s+/g, '_')}` : '';
  const dateStr = formatMilitaryDate().replace(/\s/g, '_');
  return `${prefix}${safeSiteName}_${dateStr}.pdf`;
}
